server:
  port: 3001
  host: "localhost"
  perMessageDeflate: {
    zlibDeflateOptions: {
      chunkSize: 1024,
      memLevel: 7,
      level: 3
    },
    zlibInflateOptions: {
      chunkSize: 10 * 1024
    },
    clientNoContextTakeover: true,
    serverNoContextTakeover: true,
    serverMaxWindowBits: 10,
    concurrencyLimit: 10
  }
socket:
  path: "/socket.io"
paths:
  public: "./public"
routes:
  - method: GET
    path: "/"
    file: "index.html"
  - method: GET
    path: "/room"
    file: "pages/room.html"
  - method: GET
    path: "/game"
    file: "pages/game.html"
  - method: GET
    path: "/join"
    file: "pages/enter-name.html"